name: test-kikit
on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'
jobs:
  test:
    name: "Run KiKit tests"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        kicad-version: [v5, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-kicad
        with:
          kicad-version: ${{ matrix.kicad-version }}
      - name: Install dependencies and KiKit
        run: |
          sudo apt-get -qq install --yes --no-install-recommends \
            zip inkscape make git libmagickwand-dev \
            libgraphicsmagick1-dev libmagickcore-dev \
            openscad bats
          sudo python -m pip install PcbDraw
          sudo python -m pip install -e .\[dev\]
      - run: make test
      - run: make doc
      - run: sudo make package
  deploy_docker:
    name: "Build and deploy Docker container"
    runs-on: ubuntu-20.04
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2 # Required for kikit version estimation
        with:
          fetch-depth: 0 # = fetch all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: . # We need path context, so .git gets included
          push: true
          tags: yaqwsx/kikit:nightly
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


